### ISSUE TITLE
is trixi installation required?

### ISSUE THREAD

**Issue by jayurbain** [MIC-DKFZ/basic_unet_example#11]
$ pip3 install -r requirements.txt
$ python3 -m visdom.server # ran until files downkloaded
$ python3 run_train_pipeline.py
Traceback (most recent call last):
  File "run_train_pipeline.py", line 20, in <module>
    from configs.Config_unet import get_config
  File "/home/jupyter/basic_unet_example/configs/Config_unet.py", line 20, in <module>
    from trixi.util import Config
ModuleNotFoundError: No module named 'trixi'

Any direction would be appreciated. Thanks.

**Comment by elpequeno** [comment]
Hey. Sorry for the delay. We are actually just working on the requirements. They are out of date, unfortunately. Try installing just the  first 7 lines of requirements.txt (so basically everything that has no comment in front of it. And then try again. Could be that you have to install tensorboard additionally.
We hope we can provide an update soon. Let me know if it helps.
